<?php

/**
 * Implements hook_leaflet_map_info_alter().
 */
function leaflet_search_leaflet_map_info_alter(&$maps) {
  foreach ($maps as &$map) {
    if (isset($map['plugins']['search'])) {
    }
  }
}

/**
 *  Implements hook_preprocess_HOOK().
 */
function leaflet_search_preprocess_leaflet_map(&$variables) {
  if (isset($variables['map']['plugins']['search'])) {
    $variables['#attached']['library'][] = 'leaflet_search/wrapper';
  }
}
